services:
  postgres-db:
    image: postgres:17.6
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d  # For initializing multiple DBs
      - ./db/data:/var/lib/postgresql/data      # Persisted volume
    ports:
      - 7557:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/pgdata
