// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repository

import (
	"context"
)

const findAccountById = `-- name: FindAccountById :one
SELECT id, first_name, last_name, role, profile_pic_url, phone_number 
FROM accounts
WHERE id = $1
`

func (q *Queries) FindAccountById(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.ProfilePicUrl,
		&i.PhoneNumber,
	)
	return i, err
}

const findAllAccounts = `-- name: FindAllAccounts :many
SELECT id, first_name, last_name, role, profile_pic_url, phone_number
FROM accounts
`

func (q *Queries) FindAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, findAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.ProfilePicUrl,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
