// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package repository

import (
	"context"
)

const findAccountById = `-- name: FindAccountById :one
SELECT id, first_name, last_name, role, profile_pic_url, phone_number 
FROM accounts
WHERE id = $1
`

func (q *Queries) FindAccountById(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountById, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.ProfilePicUrl,
		&i.PhoneNumber,
	)
	return i, err
}

const findAllAccounts = `-- name: FindAllAccounts :many
SELECT id, first_name, last_name, role, profile_pic_url, phone_number
FROM accounts
`

func (q *Queries) FindAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, findAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.ProfilePicUrl,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccount = `-- name: InsertAccount :one
INSERT INTO accounts (
    id, first_name, last_name, role
) values (
    $1, $2, $3, $4
) returning id, first_name, last_name, role, profile_pic_url, phone_number
`

type InsertAccountParams struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Role      Role   `json:"role"`
}

func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Role,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.ProfilePicUrl,
		&i.PhoneNumber,
	)
	return i, err
}
