// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ProjectType string

const (
	ProjectTypeSchool     ProjectType = "school"
	ProjectTypeCommertial ProjectType = "commertial"
	ProjectTypeWork       ProjectType = "work"
	ProjectTypePersonal   ProjectType = "personal"
)

func (e *ProjectType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectType(s)
	case string:
		*e = ProjectType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectType: %T", src)
	}
	return nil
}

type NullProjectType struct {
	ProjectType ProjectType `json:"project_type"`
	Valid       bool        `json:"valid"` // Valid is true if ProjectType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectType) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectType), nil
}

type Role string

const (
	RoleAdmin    Role = "admin"
	RoleUser     Role = "user"
	RoleCustomer Role = "customer"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type NullRole struct {
	Role  Role `json:"role"`
	Valid bool `json:"valid"` // Valid is true if Role is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRole) Scan(value interface{}) error {
	if value == nil {
		ns.Role, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Role.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Role), nil
}

type ShowcaseType string

const (
	ShowcaseTypeNone     ShowcaseType = "none"
	ShowcaseTypeExternal ShowcaseType = "external"
	ShowcaseTypeEmbeded  ShowcaseType = "embeded"
)

func (e *ShowcaseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShowcaseType(s)
	case string:
		*e = ShowcaseType(s)
	default:
		return fmt.Errorf("unsupported scan type for ShowcaseType: %T", src)
	}
	return nil
}

type NullShowcaseType struct {
	ShowcaseType ShowcaseType `json:"showcase_type"`
	Valid        bool         `json:"valid"` // Valid is true if ShowcaseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShowcaseType) Scan(value interface{}) error {
	if value == nil {
		ns.ShowcaseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShowcaseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShowcaseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShowcaseType), nil
}

type Account struct {
	ID            string      `json:"id"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	Role          Role        `json:"role"`
	ProfilePicUrl pgtype.Text `json:"profile_pic_url"`
	PhoneNumber   pgtype.Text `json:"phone_number"`
}

type Address struct {
	ID          int64              `json:"id"`
	StreetLine1 string             `json:"street_line1"`
	StreetLine2 pgtype.Text        `json:"street_line2"`
	City        string             `json:"city"`
	State       pgtype.Text        `json:"state"`
	PostalCode  pgtype.Text        `json:"postal_code"`
	Country     string             `json:"country"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID           uuid.UUID    `json:"id"`
	Title        string       `json:"title"`
	Description  string       `json:"description"`
	GithubRepo   pgtype.Text  `json:"github_repo"`
	ShowcaseType ShowcaseType `json:"showcase_type"`
	Type         ProjectType  `json:"type"`
	Public       bool         `json:"public"`
}
