// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findAllProjects = `-- name: FindAllProjects :many
SELECT id, title, description, github_repo, showcase_type, type, public
FROM projects
`

func (q *Queries) FindAllProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, findAllProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.GithubRepo,
			&i.ShowcaseType,
			&i.Type,
			&i.Public,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findProjectById = `-- name: FindProjectById :one
SELECT id, title, description, github_repo, showcase_type, type, public 
FROM projects
WHERE id = $1
`

func (q *Queries) FindProjectById(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, findProjectById, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GithubRepo,
		&i.ShowcaseType,
		&i.Type,
		&i.Public,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (
    id, title, description, github_repo, showcase_type, type, public
) VALUES (
    uuid_generate_v4(), $1, $2, $3, $4, $5, $6
) returning id, title, description, github_repo, showcase_type, type, public
`

type InsertProjectParams struct {
	Title        string       `json:"title"`
	Description  string       `json:"description"`
	GithubRepo   pgtype.Text  `json:"github_repo"`
	ShowcaseType ShowcaseType `json:"showcase_type"`
	Type         ProjectType  `json:"type"`
	Public       bool         `json:"public"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.Title,
		arg.Description,
		arg.GithubRepo,
		arg.ShowcaseType,
		arg.Type,
		arg.Public,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.GithubRepo,
		&i.ShowcaseType,
		&i.Type,
		&i.Public,
	)
	return i, err
}
