import type { Metadata } from 'next';
import './globals.css';
import SidebarWrapper from '@/ui/navbar/sidebar-wrapper';
import { firaCode } from './fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={firaCode.variable}>
      <body
        className={`${firaCode.className} antialiased bg-brand-bg text-brand-fg flex min-h-screen`}
      >
        <SidebarWrapper title="Krystof/Jan" initialState="opened" />

        <div className="content flex-1 bg-brand-bg-dark hover:bg-brand-bg p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
